version: "3.8"
services:
  app:
    build: .
    volumes: 
      - .:/home/app
    depends_on: 
      - db
    ports: 
      - "3000:3000"
      - "9229:9229"
  db:
    image: postgres
    environment: 
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    volumes: 
      - ./pgdata:/var/lib/postgresql/data
    ports: 
      - "5432:5432"
